### ISSUE TITLE
A few documentation fixes

### ISSUE THREAD

**Issue by webmat** [logstash-plugins/logstash-filter-elasticsearch#96]
Working to fix a few documentation issues for a doc release:

- [x] Get #88 merged (text in code blocks)
- [x] #64 be a bit more explicit about how to use query_template
- [x] Give clearer example of copying multiple fields to avoid misunderstandings like #52 and #63
- [x] Fix the "HTTP setting" link in the "Compatibility Notes" section. Will be resolved by https://github.com/elastic/logstash-docs/pull/535, affecting all 3 plugins.

Note: If my next feature takes too long to get to, we may have to do a documentation-only release. This will require a version bump to be picked up and deployed.
